### ISSUE TITLE
New "nameless" servers? 

### ISSUE THREAD

**Issue by ahalabourda** [phanx-wow/LibRealmInfo#10]
I use LibRealmInfo in another addon to determine the player's current region, since Blizzard's built-in GetCurrentRegion provides an incorrect response for users who play on a region other than that of their installed client.

My understanding of LibRealmInfo's GetCurrentRegion function is that it grabs the current server ID from the player's GUID and then looks it up in its own array of server IDs, called realmData. This has worked perfectly for my addon's users for months now, but yesterday I received a new bug report.

Currently, invoking GetCurrentRegion() while on EU-Azjol-Nerub (realm ID 503) or EU-Quel'Thelas (realm ID 623) prints the error "GetCurrentRegion: could not identify realm based on player GUID Player-1396-xxxxxxxxx". Both realms present as server ID 1396.

There is no entry for 1396 in the realmData array. Is 1396 a new "nameless" server (which I learned about [here](https://github.com/phanx-wow/LibRealmInfo/issues/6)) that needs to be added to realmData, or am I misunderstanding something here?

I hope I've explained my issue sufficiently - thank you for your time.

**Comment by maxtruxa** [comment]
@ahalabourda The ID of the "nameless" server is in fact the connected realm ID. Each server... sorry, Blizzard, connected realm... can "contain" one or more realms.

```
connected realm
 |
 +-- realm
 |
 +-- realm
```

Most of the time the connected realm ID matches the realm ID of one of the realms that's part of the connected realm, but, as you already discovered, that's not always the case.

Example where the connected realm ID matches a realm ID:
```
connected realm 639
 |
 +-- 639 EU-Xavius
 |
 +-- 519 EU-Al'Akir
 |
 +-- 557 EU-Skullcrusher
```

The servers you encountered problems on:
```
connected realm 1396
 |
 +-- 503 EU-Azjol-Nerub
 |
 +-- 623 EU-Quel'Thalas
```

A quick check against the WoW Game Data API shows that out of 261 connected realms in EU/US/KR/TW (CN APIs are still down 😞) we have right now, there are 212 cases where the IDs match and 49 cases where they don't. The fact that they sometimes match is probably just for historical reasons.

Ergo, to successfully handle player GUIDs this library would need an additional dataset mapping connected realm IDs to the realms associated with them. Currently, GUID-based lookup will fail for 69 realms spread across 49 connected realms.

**Comment by Darthpred** [comment]
In Case of Azjol-Nerub it seems like the real realm id is 1396

**Comment by Phanx** [comment]
@maxtruxa If you've already got scripts working with the API, can you just post the missing data here?

If it's in the library's expected format, that's best, but if not, I can figure it out. Currently each connected group is just stored as an "1,2,3" string with the IDs separated by commas; those strings can include the connected realm IDs along with the "real" realm IDs. (See the `connectionData` table starting on line 1180.)

Otherwise, I'll add exploration of the API to my to-do list, but I can't make any promises about when I'll get to it. I haven't played WoW in 2+ years now, and am actually slightly bewildered as to why the urge suddenly struck me tonight to fix some of the low-hanging fruit out of the bug reports that keep appearing in my inbox. :woman_shrugging: 

Also, I'm very open to accepting PRs, and am happy to add you as an official contributor if that's something you'd be interested in.

**Comment by Phanx** [comment]
Disregard my previous comment; I'm just writing a scraper to collect all the data from the API and copy it into the addon. I'll publish the scraper and update the library when it's done.

**Comment by Phanx** [comment]
Should be fixed. LibRealmInfo is now using data scraped from the Battle.net Developer API (except for Chinese realms, which aren't supported by the dev API, and are still using the old hand-compiled data) which seems to include all of the anonymous servers used to host connected realms.
