### ISSUE TITLE
CN Realm

### ISSUE THREAD

**Issue by LiangYuxuan** [phanx-wow/LibRealmInfo#17]
Hello, I'm from China and willing to help with Chinese realm info.

[Here](https://www.battlenet.com.cn/forums/zh/wow/topic/9127232633) is the connected realm info from official forum. But I don't know how to export the realm info by API and need your help.

**Comment by Phanx** [comment]
This is the tool I use to get the info from the API:

https://github.com/phanx-wow/realminfo-scraper#requirements

Download the tool and unpack the ZIP file somewhere, then follow the instructions under "Requirements" to set it up and get access to the Battle.net API. Finally, you'll need to edit the `constants.js` file and _remove_ the `// ` in front of "cn" on line 4, and _add_ `// ` in front of the other regions on lines 5-8 since your Chinese account probably doesn't have API access to non-Chinese regions. Then you can run the tool with `npm start` and send me the files it generates; the API is rate-limited, so it takes about 10 minutes to get all the data.

Let me know if you need more detailed instructions, or if you run into any issues.

**Comment by LiangYuxuan** [comment]
I run `npm start`, and get following error.

> (node:69589) UnhandledPromiseRejectionWarning: FetchError: invalid json response body at https://gateway.battlenet.com.cn/data/wow/realm reason: Unexpected end of JSON input

It seems like failing to get returns from `https://gateway.battlenet.com.cn/data/wow/realm/?namespace=dynamic-cn`. I tried this and get 403

```json
{
"code": 403,
"type": "BLZWEBAPI00000403",
"detail": "Forbidden"
}
```

**Comment by Phanx** [comment]
LibRealmInfo has a new maintainer. Please reopen any issues or PRs that are still relevant here:
https://github.com/janekjl/LibRealmInfo
